### ISSUE TITLE
Unexpected results with the OF direction

### ISSUE THREAD

**Issue by krupartea** [mcv-m6-video/class2023#1]
Arrows directions that I see on my quiver-plot visualization of the given OF estimation:

![image](https://user-images.githubusercontent.com/48570933/224543129-72c0bd3a-9fb0-4143-b3d0-ce3d44a8a72a.png)

Differ from the given on slides

![image](https://user-images.githubusercontent.com/48570933/224543669-ceaafa7b-3cd7-41e0-8295-793630d8c179.png)

Maybe I am doing something wrong with the reading\interpreting the given estimated offsets .png's?
My code for it is:
```
img = cv2.imread(path)
img = img.astype(np.int16)
img -= 128  # decode png to absolute offset
plt.quiver(img[::4, ::4, 1], img[::4, ::4, 2])
```

Here, for example, I visualize the direction with the hue. And both left and right parts of the street are moving the same direction, which can not be true:
![image](https://user-images.githubusercontent.com/48570933/224543883-0efe1a21-19f1-41f8-9d9e-e412d9bfb168.png)

**Comment by krupartea** [comment]
Oh, looks like I should read image with other option. Investigating it...

**Comment by rmorros** [comment]
Closed
