### ISSUE TITLE
Task 3 - Cameras from Seq 1 and Seq 4

### ISSUE THREAD

**Issue by alvaro-budria** [mcv-m6-video/class2023#13]
It seems there is a mismatch between the camera ids from the tables on the slides, and the actual camera indices.
In the slides we find, for Seq1:

![Screenshot from 2023-04-11 16-10-13](https://user-images.githubusercontent.com/48391578/231190063-775727c4-4515-41bb-b132-15e062245910.png)

but in the provided data, Seq1 has cameras 001 to 005.

A similar thing happens with Seq4, but this time, Seq4 has way more than 6 cameras.

Should we report the results in the same table and indicate which cameras we chose?

**Comment by jrhupc** [comment]
Sorry, this might be too late now but hopefully you added the needed columns to reflect the correct cameras for each sequence (it was just a "copy&paste" problem).
