### ISSUE TITLE
Doubt computing mean IoU

### ISSUE THREAD

**Issue by LeBrav** [mcv-m6-video/class2023#2]
When computing the IoU of a frame, we need to consider the following right?

- A ground truth annotation can only be used once, by the detection with the maximum IoU.
- If a ground truth annotation is not intersecting (IoU = 0) with any detection bounding box, then its IoU is 0. We must include this ground truth annotation with 0 IoU in the average IoU of the frame. For example, if we have three ground truth annotations with IoU values of 1, 0.5, and 0, respectively, then the mean IoU for the frame is 0.5 and not 0.75.

**Comment by jrhupc** [comment]
Hi @LeBrav 

Yes to both!

**Comment by Atenrev** [comment]
I'd like to reopen the issue to ask whether we should also consider the False Positives (aka pred boxes that do not intersect with any gt box) in the computation.

**Comment by jrhupc** [comment]
Hi,

Yes, for now you also should include false positives. That way the IoU will
be penalised  both with false positives and false negatives.

We will further discuss this in class.
