### ISSUE TITLE
No detections in ground truth

### ISSUE THREAD

**Issue by 0Miquel** [mcv-m6-video/class2023#3]
Hello,
we were evaluating task 1 when we have realized that if we do not consider the parked cars we find some empty ground truth detections.
Like this one:
![0877](https://user-images.githubusercontent.com/48658941/226095171-eb8269fe-bbbf-4743-88ee-93119be0b88e.png)

How should we compute the mAP and mIoU of these frames? Should we skip them and not consider them in the evaluation?

**Comment by rmorros** [comment]
I'm not sure I understand your question. I assume that the green rectangle is an FP?
Anyway, to compute the IoU metric, you should accumulate the iou of the detections along all sequence and average using the sum of (FP+FN+TP) along all the sequence.  Then, it does not matter if a frame has GT or not. If you have a FP in this frame, you add zero to the numerator, and you increase in one (one FP) the denominator.
Does this answer your question?
