### ISSUE TITLE
[Week 3 - Task1] Question about cross-validation table for different teams with off-the-shelf model (mAP 50)

### ISSUE THREAD

**Issue by marcosmg95** [mcv-m6-video/class2023#8]
So as I understand we need to fill the table for the mAP of one of our models for fine-tuned and off-the-shelf with cross-validation. However, I do not know what "off-the-shelf" means in this case. We need to train from scratch each neural network on a percentage of the data, or just make the predictions?

**Comment by jrhupc** [comment]
You mean in task 1.4? if so:

You do not need to train off-the-shelf models. Just compare the fine-tuned
model with off-the-shelf in the same tests (using k-fold) so you can
evaluate the losses/gains of fine running in this case.

Regards
