### ISSUE TITLE
[Week 3] - Annotations format

### ISSUE THREAD

**Issue by alvaro-budria** [mcv-m6-video/class2023#9]
Hi all,

in the annotation task, we used CVAT to filter out automatic detections and exported the resulting annotations from there. CVAT offers several output formats. We have chosen KITTI and Pascal VOC.

If we are not mistaken, the second one is the correct format for this week. Is this so? We are unsure because CVAT generated for us a set of XML files, one per frame, rather than a single XML frame for all frames (as was given by the professors). Is this OK?

Thanks

**Comment by rmorros** [comment]
Hi,
Pascal VOC is OK. No problem with a XML per frame, we can convert later.
